/*
===============================================================================
Step 5: Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT
    country,
    COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customers DESC

-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_Customers DESC

-- Find total products by category
SELECT
    category,
    COUNT(product_key) AS Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_Products DESC

-- What is the average costs in each category?
SELECT
    category,
    AVG(cost) AS Avg_Cost
FROM gold.dim_products
GROUP BY category
ORDER BY Avg_Cost DESC

-- What is the total revenue generated for each category?
SELECT
    p.category,
    SUM(s.sales_amount) AS Total_Revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON s.product_key = p.product_key
GROUP BY category
ORDER BY Total_Revenue DESC

-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS Total_Revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY Total_Revenue DESC

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    COUNT(quantity) AS Sold_Distribtion
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Sold_Distribtion DESC